---
title: "Homework #4 - Data Wrangling"
author: "your name"
output: html_document
---


**Change your name above and save the file.  Also, install the following **
**packages (that you don't have already).  This is the last time I'll remind** 
**you of these...**

```{r setup}
library(tidyverse)
library(nycflights13)
library(mdsr)


summary(flights)
```

Note, there is a *lubridate* package that has some useful date functions, like 
`month()` and `week()`. They are particularly useful with the `label = TRUE` 
option. Feel free to play around with it, but this package is not required to 
complete this assignment.

**Problem 1) The `nycflights` package contains data on all flights from the **
**New York City area in 2013.  Use the `flights` data frame to answer the ** **following...**

a) What month had the highest proportion of canceled flights? (as recorded by a 
missing departure or arrival time)

b) What month had the lowest proportion of canceled flights?

c) Interpret seasonal patterns of canceled flights.

**Problem 2) Continuing with the `nycflights` data...**

a) What plane (specified by `tailnum`) traveled the most times from NYC airports 
in 2013?

b) Plot the number of trips per week over the year for the plane with the most 
times traveled. Make sure to label the axes appropriately and add a title to the 
graph. Comment on what you observe.

**Problem 3) The `Violations` data set in the `mdsr` package contains **
**information regarding the outcome of health inspections of restaurants in **
**NYC. Use these data to calculate the median violation score by zip code for **
**zip codes in Manhattan with 50 or more inspections. What pattern do you see **
**between the number of inspections and the median score?**



