---
title: "Text Data - in class exercise"
author: "YOUR NAME HERE"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(mdsr)
library(janeaustenr)

books <- austen_books()
unique(books$book)
```

1. Use the `babynames` data table from the babynames package to find the 10 most 
popular:
    a. Boys' names ending in a vowel.
    b. Girls' names ending in consonate.
    b. Names ending with joe, jo, Joe, or Jo (e.g., Billyjoe).
    c. Which names, if any, include any punctuation in them (i.e. not "a" to "z")
    d. How many names have more than one word in them (i.e. there is a space or
    other punctuation in it)?
2. Using the `janeaustenr` package and the `austen_books()` function to get 
the text from Jane Austen's books find:
    a. How many books are in the dataset?
    b. How many lines are in each book in the dataset?
    c. How many words are there in each book in the dataset?
    d. How many unique words are there in each book in the dataset?
    e. What words are used the most frequently in "Pride & Prejudice?"
    f. Removing the stop-words, which words are used the most frequently?
    g. Create a word cloud of the most frequently used words.
    h. Create a bar chart of the most frequently used words. 