---
title: "What's Really Warming the World?"
subtitle: "A Data Visualization Recreation"  
author: "Jake Rozran"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include = FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width = 9, fig.height = 3.5, fig.retina = 3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
```

```{r xaringan-themer, include = FALSE, warning = FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF"
)
```

```{r data, include = FALSE}
library(dplyr)
library(readr)
library(ggplot2)
library(lubridate)

temp_dat <- read_csv("https://data.giss.nasa.gov/gistemp/graphs_v3/graph_data/GISTEMP_Seasonal_Cycle_since_1880/graph.csv", skip = 1)

temp_dat <- temp_dat %>% 
    mutate(year = as_date(paste0(substr(Year, 1, 4), "-01-01"))) %>% 
    filter(year >= as_date("1880-01-01") & 
               year < as_date("2006-01-01"))
    group_by(year) %>% 
    summarise(avg_temp = mean(Anomaly))

starting_temp <- as.numeric(temp_dat %>% 
                                filter(year == min(temp_dat$year)) %>% 
                                summarise(avg_temp = mean(avg_temp)))

avg_1880_1910 <- as.numeric(temp_dat %>% 
                                filter(year >= as_date("1880-01-01") & 
                                           year < as_date("1911-01-01")) %>% 
                                summarise(avg_temp = mean(avg_temp)))

edit <- -1 * (starting_temp - avg_1880_1910)

temp_dat$avg_temp <- temp_dat$avg_temp - avg_1880_1910

ggplot(temp_dat, aes(x = year, y = avg_temp)) + 
    geom_line() + 
    geom_hline(yintercept = 0)

temp_dat
```

---

class: center, middle

# The Initial Data Visualization

[Let's take a look at the original.](https://www.bloomberg.com/graphics/2015-whats-warming-the-world/)

